### ISSUE TITLE
Warning on node server BE

### ISSUE THREAD

**Issue by roestigraben** [mohammadali0120/nuxt-express-postgres-authentication#1]
Hi, after install of the package I get a warning

UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of undefined at exports.getUser

in the nuxt-express-postgres-authentication/backend/app/controllers/auth.controller.js:117:16

The application stay in spinning mode.

Help needed!

BTW, excellent initiative to show a real application setup for the auth-next module with refresh handling! Very appreciated.

**Comment by mohammadali0120** [comment]
Hi, Thanks you are very kind
I registered and also logged in and logged out frequently but I didn't face with this error except for one time and I didn't realize why it happened, but to prevent this problem according to the error you can add an `if` condition before` res. status` like below:

```js
exports.getUser = async (req, res, next) => {
  if (user) {
    res.status(200).json({
      user: {
        id: user.id,
        fullname: user.fullname,
        email: user.email,
      },
    });
  }
};
```

**Comment by roestigraben** [comment]
Thanks a lot!
Just another thing. Have you noticed that your app is not doing the automatic token refresh. It works well but it is still basically just a "normal" login app.

The doc says "Refresh Controller can be initialized in a scheme to add refresh support." but also it says "warning IMPORTANT It can only be used inside a scheme". Have you tried this out yourself?

Again many thanks

**Comment by mohammadali0120** [comment]
Your welcome, it does support access token automatic updating but automatic refresh token updating no it doesn't, there are so many ways to do refresh token updating as well but I just wanted to keep this app normal and simple

**Comment by roestigraben** [comment]
OK, as it works, I think I can live with it. And thanks also for the hint on localStorage not being a good solution.
