### ISSUE TITLE
Issue with multiple users

### ISSUE THREAD

**Issue by Journeytojah** [mohammadali0120/nuxt-express-postgres-authentication#3]
If you open a second window and log in, it will assign the second user details to the first window.

From what I can tell this is because of https://github.com/mohammadali0120/nuxt-express-postgres-authentication/blob/15368c5b96df7ecbe15eba45ba794df29488d7fa/backend/app/controllers/auth.controller.js#L50

The user gets set every time someone logs in.

Any way to fix this so I can still use Nuxt auth?

**Comment by mohammadali0120** [comment]
I believe it's not a bug or something like this, it's way of implementing in back-end and a user only can login with one account in a browser, and also i suppose is the standard way for it.
